#pragma once

/**
 *
 * DO NOT MODIFY THIS FILE - GENERATED BY THE ITEM EDITOR
 *
 * The constants defined here are used to refer to specific items in the game code.
 * They're generated using the Constant field in the item editor.  The constant field
 * is pre-pended with SFITEM_ to make the constant name.
 *
 */

#define SFITEM_WHININGORB 16
#define SFITEM_DELUXECUPHOLDERS 179
#define SFITEM_TURBOBOOST 182
